### ISSUE TITLE
Publishing discrepancies

### ISSUE THREAD

**Issue by daesthelos** [Bespin-AF/a2d2-android#46]
# Application Quality Standards
__Standards checklist__: https://developer.android.com/docs/quality-guidelines/core-app-quality

The issues below are referenced by their corresponding ID. As an example, Standard Design would be referenced as __`[UX-B1]`__.

### ~~[FN-U1] [FN-U2]~~ 
__Issue__: Application does not support landscape mode well
__Fix__: Add ` android:screenOrientation="portrait" ` to the Android Manifest
- [x] *__Resolved with pull request #47__*

### [PS-P1]
__Issue__: Application currently does not implement progress indicators
__Fix__: Implement [`ProgressBar`](https://developer.android.com/reference/android/widget/ProgressBar) and potentially [`AsyncTask`](https://developer.android.com/reference/android/os/AsyncTask)s where resources take time to load or require api calls

__Material Design Doc:__ https://material.io/design/components/progress-indicators.html

>Determinate indicators display how long a process will take. They should be used when the process completion rate can be detected.
>
>Indeterminate indicators express an unspecified amount of wait time. They should be used when progress isn’t detectable, or if it’s not necessary to indicate how long an activity will take.

- [x]  *__Resolved with pull request #50__*

### ~~[PS-P2]~~
__Issue__: Application currently does not pass [`StrictMode`](https://developer.android.com/reference/android/os/StrictMode.html) test
__Fix__: Requires in-depth testing and logging
- Thread policy flashes when clicking "Request Driver" on the `Rider_RequestRide` page
- VM policy kills the application when navigating to Rules page

- [x] Completed

__Note:__ This standard is acceptable to skip according to @Medlinator 

### ~~[PS-B1] [GP-P3]~~
__Issue__: Cannot properly test [Doze and App Standby](https://developer.android.com/training/monitoring-device-state/doze-standby.html#testing_doze_and_app_standby)
__Fix__: Requires more research

- [x] Completed

__Note:__ This standard is acceptable to skip according to @Medlinator 

### [SC-N2]
__Issue__: Application does not declare a network security configuration
__Fix__: Consult the [network security configuration](https://developer.android.com/training/articles/security-config.html) documentation and implement necessary components
- Most likely the default settings are acceptable; the only thing we might consider is opting out of cleartext traffic, but it should be unnecessary since firebase uses https.

- [x] *__Resolved with pull request #49__*

**Comment by daesthelos** [comment]
@Medlinator we should be good for app submission
